/**
 * Orion Agent Core Module
 *
 * Public streaming entry point for Orion.
 *
 * Story 2.2 refactors the canonical loop into `src/agent/loop.ts`.
 * This module remains the stable API used by Slack handlers.
 *
 * @see Story 2.1 - Anthropic API Integration
 * @see AC#1 - Messages passed to Anthropic API via messages.create() with streaming
 * @see AC#3 - Response streamed back to Slack
 * @see AC#5 - Response time 1-3 seconds (NFR1)
 */

import { executeAgentLoop } from './loop.js';
import type { LangfuseTrace } from '../observability/langfuse.js';
import type { NewLangfuseSpan } from '../observability/tracing.js';
import type { ContextSource } from './gather.js';
// Story 8.1: Import DocumentCitation from canonical location
import type { DocumentCitation } from '../slack/citations/index.js';
import { randomUUID } from 'node:crypto';
import { executeTool as executeToolWithPolicies } from '../tools/executor.js';
import { executeToolCall } from '../tools/router.js';
import { getMcpServerConfigs } from '../config/mcp-servers.js';
import { setOrionSandboxContext, clearOrionSandboxContext } from '../tools/orion-sandbox/index.js';

/**
 * Context for agent execution.
 * Includes thread history, user info, and optional trace ID for observability.
 */
export interface AgentContext {
  /** Conversation history from the thread */
  threadHistory: Array<{ role: 'user' | 'assistant'; content: string }>;
  /** Slack user ID */
  userId: string;
  /** Slack channel ID */
  channelId: string;
  /** Slack thread timestamp for container lifecycle tracking (Story 6.3) */
  threadTs?: string;
  /** Langfuse trace ID for observability correlation */
  traceId?: string;
}

/**
 * Document block for user-uploaded files.
 * @see Story 8.3 - Slack File Ingestion for Claude Context
 */
export interface DocumentBlockParam {
  type: 'document';
  source: {
    type: 'file';
    file_id: string;
  };
  title?: string;
  citations?: { enabled: boolean };
}

/**
 * Options for running the Orion agent.
 */
export interface AgentOptions {
  /** Agent execution context */
  context: AgentContext;
  /** System prompt for the agent */
  systemPrompt: string;
  /** Optional Langfuse trace/span for phase-level spans (Story 2.2) - accepts both legacy and new SDK types */
  trace?: LangfuseTrace | NewLangfuseSpan;
  /**
   * Optional status hook (Story 2.2 FR47, Story 7.3 AC1-AC5).
   *
   * @see Story 7.3 - Contextual Tool Feedback
   */
  setStatus?: (params: {
    phase: 'gather' | 'act' | 'tool' | 'verify' | 'final';
    toolName?: string | null;
    /** Tool input for query extraction (Story 7.3 AC1) */
    toolInput?: Record<string, unknown>;
    /** All tools when parallel execution (Story 7.3 AC4) */
    allTools?: Array<{ name: string; input: Record<string, unknown> }>;
  }) => void | Promise<void>;
  /**
   * Document blocks from user-uploaded files (Story 8.3).
   * These are prepended to the first user message per Anthropic's document understanding API.
   * @see AC#13 - Include document blocks in messages array before calling agent loop
   */
  documentBlocks?: DocumentBlockParam[];
}

/**
 * Source gathered during the gather phase.
 * Re-exported from gather.ts for convenience.
 */
export type { ContextSource } from './gather.js';

/**
 * Document citation from Anthropic Citations API.
 * Re-exported from canonical location for convenience.
 *
 * @see Story 8.1 - Citations & Sources Unification
 * @see ../slack/citations/types.ts for the canonical definition
 */
export type { DocumentCitation } from '../slack/citations/index.js';

/**
 * Result metadata from agent execution.
 * Available after the generator completes.
 */
export interface AgentResult {
  /** Total input tokens used */
  inputTokens: number;
  /** Total output tokens generated */
  outputTokens: number;
  /** Execution duration in milliseconds */
  durationMs: number;
  /** Whether NFR1 (1-3s response time) was met */
  nfr1Met: boolean;
  /** Sources gathered during the gather phase (Story 2.7) */
  sources?: ContextSource[];
  /**
   * File IDs generated by code execution (PTC skills).
   * Handler should upload these to Slack using SlackFileUploader.
   * @see Story 6.6 - Files API Slack Integration (AC#7)
   */
  generatedFileIds?: string[];
  /**
   * Document citations from Anthropic Citations API.
   * Empty array if no documents sent or no citations in response.
   * @see Story 8.1 - Citations & Sources Unification (AC#4)
   */
  documentCitations?: DocumentCitation[];
}

/**
 * Run the Orion agent with a user message.
 *
 * Uses Anthropic's streaming messages API for real-time response delivery.
 * Yields text chunks as they arrive for immediate streaming to Slack.
 *
 * @param userMessage - The user's message text
 * @param options - Agent context and configuration
 * @yields Text chunks from the agent response
 *
 * @example
 * ```typescript
 * const response = runOrionAgent('Hello!', {
 *   context: { threadHistory: [], userId: 'U123', channelId: 'C456' },
 *   systemPrompt: 'You are Orion, a helpful assistant.',
 * });
 *
 * for await (const chunk of response) {
 *   await streamer.append(chunk);
 * }
 * ```
 */
export async function* runOrionAgent(
  userMessage: string,
  options: AgentOptions
): AsyncGenerator<string, AgentResult, undefined> {
  const effectiveTraceId = options.context.traceId ?? randomUUID();

  const loop = executeAgentLoop(userMessage, {
    context: { ...options.context, traceId: effectiveTraceId },
    systemPrompt: options.systemPrompt,
    trace: options.trace,
    setStatus: options.setStatus,
    // Story 8.3: Pass document blocks to agent loop
    documentBlocks: options.documentBlocks,
    executeTool: async ({ name, toolUseId, input }) => {
      const args =
        input && typeof input === 'object' && !Array.isArray(input)
          ? (input as Record<string, unknown>)
          : null;

      if (!args) {
        return JSON.stringify({
          success: false,
          error: {
            code: 'TOOL_INVALID_INPUT',
            message: 'Tool input must be an object',
            retryable: false,
          },
        });
      }

      // Look up server-specific timeout for MCP tools (e.g., video generation needs 180s)
      let timeoutMs: number | undefined;
      if (name.includes('__')) {
        const serverName = name.split('__')[0];
        const serverConfig = getMcpServerConfigs().find((s) => s.name === serverName);
        if (serverConfig?.requestTimeoutMs) {
          timeoutMs = serverConfig.requestTimeoutMs;
        }
      }

      const isOrionSandbox = name === 'orion_sandbox';
      if (isOrionSandbox) setOrionSandboxContext({ traceId: effectiveTraceId });
      try {
        const result = await executeToolWithPolicies(
          name,
          toolUseId,
          args,
          executeToolCall,
          { traceId: effectiveTraceId, timeoutMs }
        );

        // The agent loop expects tool_result.content to always be a string.
        // We pass success payload or formatted error message (AC#6).
        return result.success ? result.data : result.error.message;
      } finally {
        if (isOrionSandbox) clearOrionSandboxContext();
      }
    },
  });

  // NOTE: for-await-of does NOT expose the generator's return value.
  // We manually consume to preserve the AgentResult return value contract.
  while (true) {
    const next = await loop.next();
    if (next.done) {
      return next.value;
    }
    yield next.value;
  }
}

/**
 * Rough token estimate for pre-call planning.
 * Uses ~4 chars per token as approximation.
 *
 * Note: Actual token counts are available from `stream.finalMessage().usage`
 * after the API call completes. This function is useful for pre-flight
 * estimates (e.g., context compaction decisions).
 *
 * @param text - Text to estimate tokens for
 * @returns Estimated token count
 *
 * @see Story 2.6 - Context Compaction (uses this for pre-compaction estimates)
 */
export function estimateTokens(text: string): number {
  return Math.ceil(text.length / 4);
}

