#!/usr/bin/env python3
"""
AI Enablement Overview - Samba TV
Demo script showcasing the new component-based primitives API.

Generated by Barry (Quick Flow Solo Dev) - 2026-01-07
"""

import os
import sys

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from samba_pptx import SambaPresentation, SambaColors

def create_ai_enablement_deck():
    """Create an AI Enablement Overview presentation for Samba TV."""

    # Initialize presentation with fallback fonts (in case Season fonts not installed)
    prs = SambaPresentation(theme="dark", use_fallback_fonts=True)

    # =========================================================================
    # SLIDE 1: Title Slide
    # =========================================================================
    slide1 = prs.add_slide()

    # Left accent bar (white instead of accent)
    prs.add_accent_bar(slide1, position="left", thickness=0.015, color="white")

    # Main title - positioned center-left
    prs.add_headline(slide1, "AI Enablement\nInitiative",
                     x=0.06, y=0.30, width=0.7,
                     size="large", color="white", align="left")

    # Subtitle (white instead of accent)
    prs.add_body_text(slide1, "Transforming How Samba Works with AI",
                      x=0.06, y=0.58, width=0.65,
                      size="subhead", color="white")

    # Date/presenter info
    prs.add_body_text(slide1, "Q1 2026  |  Technology Organization",
                      x=0.06, y=0.88, width=0.5,
                      size="caption", color="gray")

    # Decorative circles (grays/white - no accent)
    prs.add_circle(slide1, x=0.88, y=0.20, size=0.10, fill="white")
    prs.add_circle(slide1, x=0.78, y=0.35, size=0.06, fill="gray")
    prs.add_circle(slide1, x=0.92, y=0.42, size=0.04, fill="#404040")

    # Logo (using add_logo_to_slide method)
    prs.add_logo_to_slide(slide1, position="bottom-right", size="medium")

    # =========================================================================
    # SLIDE 2: Key Metrics Dashboard
    # =========================================================================
    slide2 = prs.add_slide()

    # Title
    prs.add_headline(slide2, "AI Adoption at Scale",
                     x=0.05, y=0.08, width=0.9,
                     size="medium", color="white")

    # Line under title (white instead of accent)
    prs.add_line(slide2, start=(0.05, 0.18), end=(0.35, 0.18),
                 color="white", thickness=3)

    # Metrics row - 4 columns using add_metric with proper spacing
    metrics = [
        ("156", "ACTIVE USERS", True),
        ("12.5K", "HOURS SAVED", True),
        ("847K", "LINES OF CODE", False),
        ("32%", "ACCEPTANCE RATE", False),
    ]

    col_width = 0.22
    start_x = 0.05
    gap = 0.02

    for i, (value, label, accent) in enumerate(metrics):
        x_pos = start_x + i * (col_width + gap)
        prs.add_metric(slide2, value, label,
                       x=x_pos, y=0.28, width=col_width,
                       accent=accent, value_size="large", label_size="micro")

    # Bottom section - key insight
    prs.add_rectangle(slide2, x=0.05, y=0.65, width=0.9, height=0.25,
                      fill="gray", opacity=0.3)

    prs.add_body_text(slide2, "KEY INSIGHT",
                      x=0.08, y=0.68, width=0.3,
                      size="caption", color="accent")

    prs.add_body_text(slide2,
                      "AI tools have become integral to daily workflows. "
                      "Engineers using Claude Code report 3x faster code reviews "
                      "and significant reduction in context-switching overhead.",
                      x=0.08, y=0.74, width=0.84,
                      size="body", color="white")

    prs.add_logo_to_slide(slide2, position="bottom-right", size="small")

    # =========================================================================
    # SLIDE 3: Three Pillars
    # =========================================================================
    slide3 = prs.add_slide()

    # Title
    prs.add_headline(slide3, "Three Pillars of AI Enablement",
                     x=0.05, y=0.06, width=0.9,
                     size="medium", color="white")

    # Three columns with accent bars and content
    pillars = [
        ("Tools &\nInfrastructure", [
            "Claude Code + Cursor",
            "MCP server ecosystem",
            "n8n automation",
            "Custom integrations"
        ]),
        ("Training &\nAdoption", [
            "Weekly AI Office Hours",
            "Hands-on workshops",
            "Best practices library",
            "Champions program"
        ]),
        ("Governance &\nSecurity", [
            "Data classification",
            "Approved tool list",
            "Usage monitoring",
            "Compliance alignment"
        ]),
    ]

    col_width = 0.28
    start_x = 0.05
    gap = 0.035

    for i, (title, items) in enumerate(pillars):
        x_pos = start_x + i * (col_width + gap)

        # Accent bar at top of column
        prs.add_rectangle(slide3, x=x_pos, y=0.18, width=col_width, height=0.006,
                          fill="accent")

        # Pillar number
        prs.add_body_text(slide3, str(i + 1),
                          x=x_pos, y=0.22, width=0.05,
                          size="large", color="accent", align="left")

        # Pillar title (next to number)
        prs.add_body_text(slide3, title,
                          x=x_pos + 0.04, y=0.22, width=col_width - 0.04,
                          size="body", color="white")

        # Bullet points - lower on slide with more room
        prs.add_bullets(slide3, items,
                        x=x_pos, y=0.38, width=col_width, height=0.45,
                        size="caption", color="white", spacing=8)

    prs.add_logo_to_slide(slide3, position="bottom-right", size="small")

    # =========================================================================
    # SLIDE 4: Roadmap
    # =========================================================================
    slide4 = prs.add_slide()

    # Title
    prs.add_headline(slide4, "2026 Roadmap",
                     x=0.05, y=0.08, width=0.9,
                     size="medium", color="white")

    # Timeline visualization
    # Horizontal line
    prs.add_line(slide4, start=(0.1, 0.35), end=(0.9, 0.35),
                 color="gray", thickness=2)

    # Quarter markers with circles and labels
    quarters = [
        ("Q1", "Foundation", ["Tool rollout", "Training launch", "Metrics baseline"]),
        ("Q2", "Scale", ["Department expansion", "Custom agents", "ROI tracking"]),
        ("Q3", "Optimize", ["Workflow automation", "Best practices v2", "Champions tier 2"]),
        ("Q4", "Transform", ["AI-first processes", "Org-wide adoption", "Innovation labs"]),
    ]

    for i, (quarter, phase, items) in enumerate(quarters):
        x_pos = 0.15 + i * 0.22

        # Circle marker on timeline
        prs.add_circle(slide4, x=x_pos, y=0.35, size=0.03,
                       fill="accent" if i == 0 else "gray")

        # Quarter label above
        prs.add_body_text(slide4, quarter,
                          x=x_pos - 0.03, y=0.25, width=0.08,
                          size="subhead", color="accent" if i == 0 else "white",
                          align="center")

        # Phase name
        prs.add_body_text(slide4, phase,
                          x=x_pos - 0.06, y=0.40, width=0.14,
                          size="body", color="white", align="center")

        # Items below
        prs.add_bullets(slide4, items,
                        x=x_pos - 0.08, y=0.48, width=0.18, height=0.35,
                        size="caption", color="gray")

    # Current quarter indicator
    prs.add_body_text(slide4, "WE ARE HERE",
                      x=0.12, y=0.18, width=0.1,
                      size="micro", color="accent", align="center")
    prs.add_line(slide4, start=(0.15, 0.22), end=(0.15, 0.32),
                 color="accent", thickness=2)

    prs.add_logo_to_slide(slide4, position="bottom-right", size="small")

    # =========================================================================
    # SLIDE 5: Call to Action
    # =========================================================================
    slide5 = prs.add_slide()

    # Left accent bar
    prs.add_accent_bar(slide5, position="left", thickness=0.02)

    # Main message
    prs.add_headline(slide5, "Get Started Today",
                     x=0.05, y=0.25, width=0.9,
                     size="large", color="white")

    # Action items
    actions = [
        "Join AI Office Hours - Fridays 12-1pm",
        "Install Claude Code from approved tools list",
        "Complete the AI Foundations training module",
        "Connect with your department's AI Champion"
    ]

    prs.add_bullets(slide5, actions,
                    x=0.05, y=0.42, width=0.6, height=0.35,
                    size="body", color="white")

    # Contact box on right
    prs.add_rectangle(slide5, x=0.68, y=0.42, width=0.27, height=0.3,
                      fill="accent", opacity=0.15, border=True, border_color="accent")

    prs.add_body_text(slide5, "QUESTIONS?",
                      x=0.70, y=0.45, width=0.23,
                      size="caption", color="accent")

    prs.add_body_text(slide5, "ai-enablement@samba.tv",
                      x=0.70, y=0.52, width=0.23,
                      size="body", color="white")

    prs.add_body_text(slide5, "#ai-help on Slack",
                      x=0.70, y=0.60, width=0.23,
                      size="body", color="white")

    # Decorative elements
    prs.add_circle(slide5, x=0.92, y=0.15, size=0.06, fill="accent")
    prs.add_circle(slide5, x=0.85, y=0.20, size=0.03, fill="gray")

    prs.add_logo_to_slide(slide5, position="bottom-right", size="medium")

    # =========================================================================
    # Save the presentation
    # =========================================================================
    output_path = os.path.expanduser("~/Desktop/AI-Enablement-Overview.pptx")
    prs.save(output_path)

    print(f"\n{'='*60}")
    print("AI ENABLEMENT OVERVIEW - GENERATED SUCCESSFULLY")
    print(f"{'='*60}")
    print(f"\nOutput: {output_path}")
    print(f"Slides: 5")
    print(f"Theme: Dark")
    print(f"\nSlide breakdown:")
    print("  1. Title slide with decorative circles")
    print("  2. Key metrics dashboard (4 KPIs)")
    print("  3. Three pillars with bullet lists")
    print("  4. 2026 roadmap timeline")
    print("  5. Call to action with contact info")
    print(f"\n{'='*60}")
    print("Open in PowerPoint or Keynote to view!")
    print(f"{'='*60}\n")

    return output_path


if __name__ == "__main__":
    create_ai_enablement_deck()
