/**
 * Skill Types
 *
 * Type definitions for the Agent Skills system.
 *
 * @see Story 6.1 - Agent Skills Loader
 * @see AC#2 - Skill name, description, instructions, tools extracted
 * @see AC#5 - Tool names validated as snake_case
 */

/** Tool name validation pattern (snake_case) */
export const TOOL_NAME_PATTERN = /^[a-z][a-z0-9_]*$/;

/**
 * Parameter definition for a skill tool.
 */
export interface SkillToolParameter {
  type: 'string' | 'number' | 'boolean' | 'array';
  description: string;
  required?: boolean;
  items?: string; // For arrays
  enum?: string[]; // For enums
}

/**
 * Tool definition within a skill.
 */
export interface SkillTool {
  name: string;
  description: string;
  parameters: Record<string, SkillToolParameter>;
}

/**
 * Script file discovered in a skill's scripts/ directory.
 * @see Story 6.1 - GKE Sandbox integration (discovery only)
 */
export interface SkillScript {
  name: string; // e.g., "search_and_aggregate.py"
  path: string; // Full path for GKE execution
  requirements?: string; // Path to requirements.txt if present
}

/**
 * Parsed skill from a SKILL.md file (full content including instructions).
 */
export interface Skill {
  name: string;
  description: string;
  version?: string;
  author?: string;
  instructions: string; // Markdown content after frontmatter
  tools?: SkillTool[];
  filePath: string; // For debugging/logging

  // GKE Sandbox integration (Story 6.1 catalogs, Story 6.2 executes)
  scripts?: SkillScript[]; // Discovered from scripts/ directory
  hasExecutableScripts: boolean;
}

/**
 * Skill metadata for startup loading (progressive disclosure level 1).
 *
 * Contains frontmatter fields only - NO instructions loaded at startup.
 * Instructions are loaded on-demand when skill is invoked.
 *
 * @see Story 6.1 AC#2 - Metadata-only loading at startup
 * @see Story 6.1 AC#4 - Skills hint injected (not full content)
 */
export interface SkillMetadata {
  name: string;
  description: string;
  version?: string;
  author?: string;
  tools?: SkillTool[];
  filePath: string; // For debugging/logging
  skillPath: string; // Directory path for on-demand instruction loading

  // GKE Sandbox integration (Story 6.1 catalogs, Story 6.2 executes)
  scripts?: SkillScript[]; // Discovered from scripts/ directory
  hasExecutableScripts: boolean;
}

/**
 * Result of skill loading operation (full skills with instructions).
 */
export interface SkillLoadResult {
  skills: Skill[];
  failures: Array<{ path: string; error: string }>;
}

/**
 * Result of skill metadata loading operation (metadata-only, no instructions).
 */
export interface SkillMetadataLoadResult {
  skills: SkillMetadata[];
  failures: Array<{ path: string; error: string }>;
}

// =============================================================================
// SKILLS API TYPES (Story 6.2)
// =============================================================================

/**
 * Skill as returned from Anthropic Skills API.
 *
 * @see Story 6.2 AC#3 - Skill appears with correct metadata and version
 */
export interface ApiSkill {
  id: string; // skill_01AbCdEfGhIjKlMnOpQrStUv
  display_title: string;
  source: 'custom' | 'anthropic';
  latest_version: string; // epoch timestamp
  created_at: string; // ISO timestamp
}

/**
 * Skill version from API.
 *
 * @see Story 6.2 AC#4 - Modified SKILL.md creates new version
 */
export interface ApiSkillVersion {
  version: string; // epoch timestamp
  created_at: string;
}

/**
 * File to upload with a skill.
 */
export interface SkillFile {
  name: string;
  content: Buffer | string;
}

/**
 * Cached skill mapping for local → API sync.
 *
 * Stored at `.skills/.cache/skills.json`.
 *
 * @see Story 6.2 Task 2.4 - Skill ID cache
 */
export interface SkillCache {
  skills: Record<
    string,
    {
      skillId: string;
      latestVersion: string;
      contentHash: string;
      lastSynced: string;
    }
  >;
}

/**
 * Container parameter for Messages API (uses snake_case per Anthropic API spec).
 *
 * @see Story 6.2 AC#2 - Container parameter includes uploaded skills
 */
export interface ContainerParameter {
  id?: string; // Reuse container across turns (from response.container.id)
  skills: Array<{
    type: 'custom' | 'anthropic';
    skill_id: string; // NOTE: snake_case, NOT camelCase
    version: string; // epoch timestamp or 'latest'
  }>;
}

/**
 * File generated by skill execution (AC#9).
 * Extracted from bash_code_execution_tool_result content blocks.
 */
export interface SkillGeneratedFile {
  file_id: string; // For Files API download
  filename?: string; // Original filename if available
}

/**
 * Result of extractFileIds() helper.
 *
 * @see Story 6.2 AC#9 - File IDs extractable from response
 */
export interface SkillExecutionFiles {
  fileIds: string[];
  files: SkillGeneratedFile[];
}

// =============================================================================
// SKILL REGISTRY TYPES (Story 6.4)
// =============================================================================

/**
 * Type of skill - built-in Anthropic or custom uploaded.
 *
 * @see Story 6.4 AC#3 - Built-in skills use name as ID
 */
export type SkillType = 'custom' | 'anthropic';

/**
 * Container skill reference for Messages API (snake_case per Anthropic API).
 *
 * @see Story 6.4 AC#4 - getContainerSkills() returns API-ready structure
 */
export interface ContainerSkillReference {
  type: SkillType;
  skill_id: string; // NOTE: snake_case for API
  version: string;
}

/**
 * Registry entry for a skill with full metadata.
 *
 * @see Story 6.4 AC#5 - getSkillMetadata returns full entry
 */
export interface SkillRegistryEntry {
  /** Local skill name (e.g., "summarize") */
  name: string;
  /** Anthropic skill ID (e.g., "skill_01AbCdEf..." or "xlsx" for built-in) */
  skillId: string;
  /** Skill type */
  type: SkillType;
  /** Latest version epoch timestamp or 'latest' */
  version: string;
  /** Content hash for change detection */
  contentHash?: string;
  /** Last sync timestamp */
  lastSynced?: string;
}


// =============================================================================
// CONTAINER LIFECYCLE TYPES (Story 6.3)
// =============================================================================

/**
 * Container state for lifecycle tracking.
 *
 * @see Story 6.3 - Container Lifecycle Manager
 */
export interface ContainerState {
  containerId: string;
  lastUsed: number; // Date.now() timestamp
}

/**
 * Configuration constants for container lifecycle.
 */
export interface ContainerLifecycleConfig {
  ttlMs: number; // 30 minutes default
  maxEntries: number; // 1000 max
  cleanupIntervalMs: number; // 5 minutes
}

